# Generated by Django 4.0 on 2022-01-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='emailid',
            new_name='email',
        ),
    ]
