# Generated by Django 4.0 on 2022-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_player_alter_fee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='Amount',
            field=models.CharField(max_length=12),
        ),
    ]
